// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB76-7RIFub-3J8QilXt1aa3fsNtKpRAP0',
    appId: '1:185199789255:web:5cbd37c6f13ea84aff2ae2',
    messagingSenderId: '185199789255',
    projectId: 'qlchild',
    authDomain: 'qlchild.firebaseapp.com',
    databaseURL: 'https://qlchild-default-rtdb.firebaseio.com',
    storageBucket: 'qlchild.firebasestorage.app',
    measurementId: 'G-XTPCVL2F71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7pOq8BJZ-y-8fLeGa5AqHsMC5fA6hUkw',
    appId: '1:185199789255:android:dd0cf5a6cc06f782ff2ae2',
    messagingSenderId: '185199789255',
    projectId: 'qlchild',
    databaseURL: 'https://qlchild-default-rtdb.firebaseio.com',
    storageBucket: 'qlchild.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmRoVGeIccudf5k_kLkld9vqMqQwsoP4s',
    appId: '1:185199789255:ios:26172f3dac35b941ff2ae2',
    messagingSenderId: '185199789255',
    projectId: 'qlchild',
    databaseURL: 'https://qlchild-default-rtdb.firebaseio.com',
    storageBucket: 'qlchild.firebasestorage.app',
    iosBundleId: 'com.example.quanLyChaCon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmRoVGeIccudf5k_kLkld9vqMqQwsoP4s',
    appId: '1:185199789255:ios:26172f3dac35b941ff2ae2',
    messagingSenderId: '185199789255',
    projectId: 'qlchild',
    databaseURL: 'https://qlchild-default-rtdb.firebaseio.com',
    storageBucket: 'qlchild.firebasestorage.app',
    iosBundleId: 'com.example.quanLyChaCon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB76-7RIFub-3J8QilXt1aa3fsNtKpRAP0',
    appId: '1:185199789255:web:65e7e6a667f0c8f5ff2ae2',
    messagingSenderId: '185199789255',
    projectId: 'qlchild',
    authDomain: 'qlchild.firebaseapp.com',
    databaseURL: 'https://qlchild-default-rtdb.firebaseio.com',
    storageBucket: 'qlchild.firebasestorage.app',
    measurementId: 'G-KFBQH6KSZE',
  );
}
